/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WagooRouteImport } from './routes/wagoo'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as MonitoramentoRouteImport } from './routes/monitoramento'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as AvendasRouteImport } from './routes/avendas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as R2avendasRouteImport } from './routes/2avendas'
import { Route as IndexRouteImport } from './routes/index'

const WagooRoute = WagooRouteImport.update({
  id: '/wagoo',
  path: '/wagoo',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoramentoRoute = MonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const AvendasRoute = AvendasRouteImport.update({
  id: '/avendas',
  path: '/avendas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const R2avendasRoute = R2avendasRouteImport.update({
  id: '/2avendas',
  path: '/2avendas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/2avendas': typeof R2avendasRoute
  '/admin': typeof AdminRoute
  '/avendas': typeof AvendasRoute
  '/mensagens': typeof MensagensRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/tasks': typeof TasksRoute
  '/wagoo': typeof WagooRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/2avendas': typeof R2avendasRoute
  '/admin': typeof AdminRoute
  '/avendas': typeof AvendasRoute
  '/mensagens': typeof MensagensRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/tasks': typeof TasksRoute
  '/wagoo': typeof WagooRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/2avendas': typeof R2avendasRoute
  '/admin': typeof AdminRoute
  '/avendas': typeof AvendasRoute
  '/mensagens': typeof MensagensRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/tasks': typeof TasksRoute
  '/wagoo': typeof WagooRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/2avendas'
    | '/admin'
    | '/avendas'
    | '/mensagens'
    | '/monitoramento'
    | '/tasks'
    | '/wagoo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/2avendas'
    | '/admin'
    | '/avendas'
    | '/mensagens'
    | '/monitoramento'
    | '/tasks'
    | '/wagoo'
  id:
    | '__root__'
    | '/'
    | '/2avendas'
    | '/admin'
    | '/avendas'
    | '/mensagens'
    | '/monitoramento'
    | '/tasks'
    | '/wagoo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R2avendasRoute: typeof R2avendasRoute
  AdminRoute: typeof AdminRoute
  AvendasRoute: typeof AvendasRoute
  MensagensRoute: typeof MensagensRoute
  MonitoramentoRoute: typeof MonitoramentoRoute
  TasksRoute: typeof TasksRoute
  WagooRoute: typeof WagooRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wagoo': {
      id: '/wagoo'
      path: '/wagoo'
      fullPath: '/wagoo'
      preLoaderRoute: typeof WagooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoramento': {
      id: '/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof MonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avendas': {
      id: '/avendas'
      path: '/avendas'
      fullPath: '/avendas'
      preLoaderRoute: typeof AvendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2avendas': {
      id: '/2avendas'
      path: '/2avendas'
      fullPath: '/2avendas'
      preLoaderRoute: typeof R2avendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R2avendasRoute: R2avendasRoute,
  AdminRoute: AdminRoute,
  AvendasRoute: AvendasRoute,
  MensagensRoute: MensagensRoute,
  MonitoramentoRoute: MonitoramentoRoute,
  TasksRoute: TasksRoute,
  WagooRoute: WagooRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
