/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AvendasRouteImport } from './routes/avendas'
import { Route as WagooRouteImport } from './routes/wagoo'
import { Route as IndexRouteImport } from './routes/index'

const AvendasRoute = AvendasRouteImport.update({
  id: '/avendas',
  path: '/avendas',
  getParentRoute: () => rootRouteImport,
} as any)
const WagooRoute = WagooRouteImport.update({
  id: '/wagoo',
  path: '/wagoo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avendas': typeof AvendasRoute
  '/wagoo': typeof WagooRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avendas': typeof AvendasRoute
  '/wagoo': typeof WagooRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avendas': typeof AvendasRoute
  '/wagoo': typeof WagooRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/avendas' | '/wagoo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/avendas' | '/wagoo'
  id: '__root__' | '/' | '/avendas' | '/wagoo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvendasRoute: typeof AvendasRoute
  WagooRoute: typeof WagooRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/avendas': {
      id: '/avendas'
      path: '/avendas'
      fullPath: '/avendas'
      preLoaderRoute: typeof AvendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wagoo': {
      id: '/wagoo'
      path: '/wagoo'
      fullPath: '/wagoo'
      preLoaderRoute: typeof WagooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvendasRoute: AvendasRoute,
  WagooRoute: WagooRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
